Add default service to Drawer
uestc-bbs-new/qshp-fe pull request #28
Opened 2023-11-21 14:59 UTC by Akejyo

左侧抽屉添加论坛服务，为了这个稍微拆分了一下Drawer/NavLink.tsx

2023-11-21 23:05 UTC, fangjue requested changes

2023-11-21 23:05 UTC, fangjue commented on bbs/src/components/Drawer/NavLinks.tsx
> +type ForumData<T extends boolean> = {
这里不如改名为`NavData`，`isDefault` 改为 `isForum`（前后的条件判断相应地改一下），这样逻辑上更准确，保存的是*导航栏*的数据，一般都是链接，版块是其中一种特殊类型。

2023-11-21 23:05 UTC, fangjue commented on bbs/src/components/Drawer/NavLinks.tsx
> +      <ListItemIcon>{/* <StarBorder /> */}</ListItemIcon>
StarBorder 是什么？

2023-11-22 01:24 UTC, Akejyo commented on bbs/src/components/Drawer/NavLinks.tsx
> +      <ListItemIcon>{/* <StarBorder /> */}</ListItemIcon>
这个一直都在好像，猜测本来是想塞个图标或者边框什么的装饰

2023-11-22 01:29 UTC, Akejyo commented on bbs/src/components/Drawer/NavLinks.tsx
> +type ForumData<T extends boolean> = {
已修改

2023-11-22 02:39 UTC, merged