Feature/guoxiang/add copy modal
uestc-bbs-new/qshp-fe pull request #45
Opened 2024-01-28 08:44 UTC by gitguoxiangyu

2024-01-28 08:56 UTC, fangjue requested changes

2024-01-28 08:56 UTC, fangjue commented on bbs/src/components/Snackbar/index.tsx
> +      if (delay) {
<Snackbar> 有 `autoHideDuration` 属性，下面也用到了，为什么还需要这样操作？

2024-01-28 08:56 UTC, fangjue commented on bbs/src/pages/Thread/Floor.tsx
> +      <CenteredSnackbar open={open} autoHideDuration={3000}>
把 useSnackbar 返回值中的 props.onClose 传给 <Snackbar>？

2024-01-28 08:56 UTC, fangjue commented on bbs/src/pages/Thread/Floor.tsx
> +                  console.log(666)
测试无误后这句 console.log 可以删除。

2024-01-28 09:05 UTC, gitguoxiangyu commented on bbs/src/components/Snackbar/index.tsx
> +      if (delay) {
当时写的时候小丑了，忘记传 `onClose` 事件了，然后 `autoHideDuration` 属性未生效，所以这样写了，我现在去改

2024-01-28 09:05 UTC, gitguoxiangyu commented on bbs/src/pages/Thread/Floor.tsx
> +                  console.log(666)
好的

2024-01-28 11:18 UTC, fangjue commented on bbs/src/pages/Thread/Floor.tsx
> +        <Alert severity="success">复制成功</Alert>
提示语：“**链接**复制成功”更合适？刚才实际i操作了一下，只有“复制成功”四个字感觉看不太明白。

2024-01-28 11:20 UTC, fangjue commented on bbs/src/pages/Thread/Floor.tsx
> +    <Box className="">
空的 className 属性删除。
`pb={1}` 保留吧，现在这样底部的“点评、回复……”紧贴底边不太好看。

2024-01-28 11:29 UTC, gitguoxiangyu commented on bbs/src/pages/Thread/Floor.tsx
> +        <Alert severity="success">复制成功</Alert>
好的

2024-01-31 23:58 UTC, fangjue commented
先合并，两个小问题我来改吧。

2024-02-01 00:03 UTC, merged

2024-02-03 10:39 UTC, gitguoxiangyu commented on bbs/src/pages/Thread/Floor.tsx
> +    <Box className="">
这个上次改完了，忘记交了

2024-02-03 10:39 UTC, gitguoxiangyu commented
不好意思，麻烦学长了，我待会手机上登个邮箱，省的漏消息