Feature/guoxiang/vote post
uestc-bbs-new/qshp-fe pull request #60
Opened 2024-02-03 10:36 UTC by gitguoxiangyu

feat: 投票贴

2024-02-03 10:37 UTC, gitguoxiangyu commented
投票贴骨架开发完成，接口、样式尚未写好，先暂时不合并，留个 pr

2024-02-03 12:11 UTC, gitguoxiangyu commented
目前投票参数构建完毕，但是当前设计稿好像没有包括各类发帖选项以及投票贴的内部选项，如，投票后结果是否可见等。因此样式待定，待设计完善后再优化

2024-02-03 14:33 UTC, fangjue commented
> 目前投票参数构建完毕，但是当前设计稿好像没有包括各类发帖选项以及投票贴的内部选项，如，投票后结果是否可见等。因此样式待定，待设计完善后再优化

不必拘泥于设计图，先把功能实现出来。可以用基本的 MUI 组件做出原型，界面优化后面再做，就像之前的登录、版块选择等页面那样。

2024-02-03 15:04 UTC, gitguoxiangyu commented
> > 目前投票参数构建完毕，但是当前设计稿好像没有包括各类发帖选项以及投票贴的内部选项，如，投票后结果是否可见等。因此样式待定，待设计完善后再优化
> 
> 不必拘泥于设计图，先把功能实现出来。可以用基本的 MUI 组件做出原型，界面优化后面再做，就像之前的登录、版块选择等页面那样。

基本功能和原型都大体写好了，就是还有几个选项的按钮没加，但是目前接口尚未调通，不知道是不是入参是否有变动或者是接口哪里没写对（接口参数目前是按照 PostThreadDetails 这个类写的）
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92166956/e1ab67a7-42e0-4491-9dfd-bee1a7bccb3b)

2024-02-03 15:52 UTC, fangjue commented
> > > 目前投票参数构建完毕，但是当前设计稿好像没有包括各类发帖选项以及投票贴的内部选项，如，投票后结果是否可见等。因此样式待定，待设计完善后再优化
> > 
> > 
> > 不必拘泥于设计图，先把功能实现出来。可以用基本的 MUI 组件做出原型，界面优化后面再做，就像之前的登录、版块选择等页面那样。
> 
> 基本功能和原型都大体写好了，就是还有几个选项的按钮没加，但是目前接口尚未调通，不知道是不是入参是否有变动或者是接口哪里没写对（接口参数目前是按照 PostThreadDetails 这个类写的） ![image](https://private-user-images.githubusercontent.com/92166956/302043578-e1ab67a7-42e0-4491-9dfd-bee1a7bccb3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzU0ODIsIm5iZiI6MTcwNjk3NTE4MiwicGF0aCI6Ii85MjE2Njk1Ni8zMDIwNDM1NzgtZTFhYjY3YTctNDJlMC00NDkxLTlkZmQtYmVlMWE3YmNjYjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE1NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZmViN2M3Yjg2ZjI0MmFkZGY5MDA1MDg4MmEwNjYzZWZlZjg5ZmQwMDcxNGIxZDg4NmI1ZmExZjhkOGQyZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PnOySMn1_Nl6ccAZyxugFIfC6DfrW3_I6aZjDBmZ0c)

刚才在 https://github.com/uestc-bbs-new/qshp-fe/issues/46#issuecomment-1925357327 提到发表投票不需要传 id，这里传了三个重复的 id，导致插入数据库时 id 冲突（截图中没看到 API 返回值，我猜是这个原因）。考虑到这个问题，刚刚提交了 uestc-bbs-new/bbs@d9210e6 （未上线）。

2024-02-04 00:36 UTC, fangjue commented
> 目前投票参数构建完毕，但是当前设计稿好像没有包括各类发帖选项以及投票贴的内部选项，如，投票后结果是否可见等。因此样式待定，待设计完善后再优化

有投票选项：
https://pixso.cn/app/editor/uQRyZL8b0vtIHfh0vYtk5Q?page-id=208%3A23363
（注意其中的“（最长可设置为 3 天）”去掉，这只是水手之家版块的规定，而不是全局的。）

2024-02-05 07:52 UTC, gitguoxiangyu commented
> > > > 目前投票参数构建完毕，但是当前设计稿好像没有包括各类发帖选项以及投票贴的内部选项，如，投票后结果是否可见等。因此样式待定，待设计完善后再优化
> > > 
> > > 
> > > 不必拘泥于设计图，先把功能实现出来。可以用基本的 MUI 组件做出原型，界面优化后面再做，就像之前的登录、版块选择等页面那样。
> > 
> > 
> > 基本功能和原型都大体写好了，就是还有几个选项的按钮没加，但是目前接口尚未调通，不知道是不是入参是否有变动或者是接口哪里没写对（接口参数目前是按照 PostThreadDetails 这个类写的） ![image](https://private-user-images.githubusercontent.com/92166956/302043578-e1ab67a7-42e0-4491-9dfd-bee1a7bccb3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzU0ODIsIm5iZiI6MTcwNjk3NTE4MiwicGF0aCI6Ii85MjE2Njk1Ni8zMDIwNDM1NzgtZTFhYjY3YTctNDJlMC00NDkxLTlkZmQtYmVlMWE3YmNjYjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE1NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZmViN2M3Yjg2ZjI0MmFkZGY5MDA1MDg4MmEwNjYzZWZlZjg5ZmQwMDcxNGIxZDg4NmI1ZmExZjhkOGQyZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PnOySMn1_Nl6ccAZyxugFIfC6DfrW3_I6aZjDBmZ0c)
> 
> 刚才在 [#46 (comment)](https://github.com/uestc-bbs-new/qshp-fe/issues/46#issuecomment-1925357327) 提到发表投票不需要传 id，这里传了三个重复的 id，导致插入数据库时 id 冲突（截图中没看到 API 返回值，我猜是这个原因）。考虑到这个问题，刚刚提交了 [uestc-bbs-new/bbs@d9210e6](https://github.com/uestc-bbs-new/bbs/commit/d9210e6) （未上线）。

API 无返回值，状态码为 400，去掉id，还是400，可能还是哪个参数没对，有没有 postman 测试接口成功的例子的 curl
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92166956/647ec7ef-bf99-467d-9441-30ba4225e853)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92166956/74a86096-22ae-4436-ac7d-c9b52482cc0b)

2024-02-05 12:18 UTC, gitguoxiangyu commented
> expiration: 5000000000，为什么会这么大？
> 
> expiration 的注释里忘了加一句 0 表示没有有效期，后面加上。



随便填的，我刚刚试了下 expiration  为 0，还是 400
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92166956/94d2a709-423f-41b2-a361-a6727b0ad86d)
我先把其他配置项填写补充一下

2024-02-05 12:33 UTC, fangjue commented
multiple: true, max_choices: 1，这两个属性矛盾了。

看来还是有必要像 https://github.com/uestc-bbs-new/qshp-fe/issues/46#issuecomment-1925353209 中说的那样，在发表投票时把 API 层面中的 multiple 属性取消，以免引起不必要的误解。

2024-02-14 07:06 UTC, gitguoxiangyu commented
> multiple: true, max_choices: 1，这两个属性矛盾了。
> 
> 看来还是有必要像 [#46 (comment)](https://github.com/uestc-bbs-new/qshp-fe/issues/46#issuecomment-1925353209) 中说的那样，在发表投票时把 API 层面中的 multiple 属性取消，以免引起不必要的误解。

确实是这个原因

2024-02-14 08:01 UTC, gitguoxiangyu commented
投票能力基本建设完成，已可以满足基本的使用，如果样式暂时不管的话，应该可以 `merge` 了

2024-02-14 08:26 UTC, fangjue commented
“计票 **天数** ”既然叫这个名字，当然只是填一个以天为单位的整数。

2024-02-14 08:37 UTC, fangjue requested changes
之前代码中的评论也看一下。

2024-02-14 08:37 UTC, fangjue commented on bbs/src/components/Editor/VoteSelection.tsx
> +                      '选择数不能低于 2，且不能大于选项数，否则帖子无法正常新增'
这个提示在这里 console.log 有什么意义？应该提交前检查并提示用户。

2024-02-14 08:37 UTC, fangjue commented on bbs/src/components/Editor/VoteSelection.tsx
> +            {/* todo: 这里是去填一个时间？还是去使用日期选择器选中一个指定的日期时间 */}
实现上的疑问不要留在代码注释里。

2024-02-14 08:40 UTC, fangjue requested changes

2024-02-14 08:40 UTC, fangjue commented on bbs/src/components/Editor/VoteSelection.tsx
> +                  expiration: Number(e.target.value),
这里应该填什么值参见 expiration 字段的注释。

2024-02-14 08:48 UTC, fangjue commented on bbs/src/components/Editor/VoteSelection.tsx
> +          label="isVote"
这里改成中文。

2024-02-14 08:50 UTC, fangjue commented on bbs/src/components/Editor/VoteSelection.tsx
> +                label="未投票时结果可见"
界面中叫做“投票后结果可见”，“未投票时结果可见”不如“投票后结果可见”直观。更新投票配置时把这个值取反。

2024-02-14 08:55 UTC, fangjue commented
`<VoteSelection>` 应当属于 `<PostOptions>` 的另一个理由：

界面上不对齐，不美观：

![image](https://github.com/uestc-bbs-new/qshp-fe/assets/4703033/b641c786-2362-4c5d-9f0d-81d2445e9f73)

2024-02-14 08:56 UTC, fangjue commented
MUI 有 `<Checkbox>`，设计图上和现有界面中的其他选项也是复选框，为什么要用 `<Switch>`？

2024-03-12 02:28 UTC, fangjue commented
投票拖的时间太久了，已合并。后面我又做了一些修改。

2024-03-12 02:28 UTC, closed without merging