Add Blacklist Page
uestc-bbs-new/qshp-fe pull request #61
Opened 2024-02-03 12:47 UTC by Akejyo

黑名单管理页面的 UI
关于该页面的搜索用户，也许可以复用顶部栏的搜索用户

2024-02-03 14:17 UTC, fangjue commented
尽量不要提交无关文件。如果要改 index.html 开头的 doctype 大小写可以单独发 Pull request；第三方 vditor 的 README.md 没有充分理由的话不要动。

2024-02-03 14:38 UTC, fangjue commented
> 关于该页面的搜索用户，也许可以复用顶部栏的搜索用户

顶部搜索栏已经优化过了，直接输入关键词而不用选择类型，未来的设想参见 https://github.com/uestc-bbs-new/bbs/issues/4#issuecomment-1902621687 。

另外“该页面”指的是黑名单？黑名单需要搜索吗？

2024-02-03 14:41 UTC, Akejyo commented
> > 关于该页面的搜索用户，也许可以复用顶部栏的搜索用户
> 
> 顶部搜索栏已经优化过了，直接输入关键词而不用选择类型，未来的设想参见 [uestc-bbs-new/bbs#4 (comment)](https://github.com/uestc-bbs-new/bbs/issues/4#issuecomment-1902621687) 。
> 
> 另外“该页面”指的是黑名单？黑名单需要搜索吗？

我看设计稿里有黑名单用户搜索，应该是搜索一个用户将其添加到黑名单

2024-02-03 15:15 UTC, fangjue commented
> > > 关于该页面的搜索用户，也许可以复用顶部栏的搜索用户
> > 
> > 
> > 顶部搜索栏已经优化过了，直接输入关键词而不用选择类型，未来的设想参见 [uestc-bbs-new/bbs#4 (comment)](https://github.com/uestc-bbs-new/bbs/issues/4#issuecomment-1902621687) 。
> > 另外“该页面”指的是黑名单？黑名单需要搜索吗？
> 
> 我看设计稿里有黑名单用户搜索，应该是搜索一个用户将其添加到黑名单

设计图上是“输入用户名，添加”，那么比较好的用户体验就是一边输入用户名一边在下拉框中显示结果/自动完成（可以尝试一下目前测试版河畔顶部的搜索，显示的帖子但道理是类似的），能不能做到这个程度取决于以后能不能有比较快的用户名搜索 API。不考虑这个“高级需求”，那么最基础的功能就是输入完整的用户名，点击添加，先做到这一步。

2024-02-28 13:00 UTC, fangjue requested changes

2024-02-28 13:00 UTC, fangjue commented on bbs/src/apis/settings/index.ts
这是什么？

2024-02-28 13:00 UTC, fangjue commented on bbs/src/apis/settings/index.ts
这是什么？

2024-02-28 13:00 UTC, fangjue commented on SSO/index.html
> +
？

2024-02-28 13:00 UTC, fangjue commented on package.json
去掉无关文件

2024-02-28 13:00 UTC, fangjue commented on pnpm-lock.yaml
去掉无关文件+1

2024-02-28 13:00 UTC, fangjue commented on bbs/src/utils/bbcode/bbcode.js
去掉无关文件

2024-03-05 12:40 UTC, fangjue commented
这个 Pull request 是关于黑名单的，头像另外再开一个 Pull request 吧。

2024-03-12 02:30 UTC, fangjue commented
已部分合并为 4441e20，去除无关文件与修改头像部分，修改头像参见 #68 。

2024-03-12 02:30 UTC, closed without merging