个人空间留言板功能
uestc-bbs-new/qshp-fe pull request #71
Opened 2024-03-31 11:06 UTC by Agnes0224

留言板的添加、更新、删除留言功能

2024-03-31 12:27 UTC, fangjue commented on bbs/src/pages/User/MessageBoard.tsx
> +      addComment({ uid: userSummary.uid, message: inputRef.current.value })
`await addComment`
addComment 是异步的，留言成功发表之后才能继续进行后面的操作（清空留言框、刷新留言列表）。

2024-03-31 12:28 UTC, fangjue commented on bbs/src/pages/User/MessageBoard.tsx
> +              {item.message}
编辑留言时，为什么旧留言要大度显示在文本框上方，而不是作为文本框的初始值？

2024-03-31 12:30 UTC, fangjue requested changes
还有一点，留言文本框是多行文本框，留言可以换行的。

2024-03-31 13:45 UTC, Agnes0224 commented
> 还有一点，留言文本框是多行文本框，留言可以换行的。

已修改

2024-04-01 11:16 UTC, fangjue approved these changes
格式化问题后面再说，先合并了。

2024-04-01 11:16 UTC, merged