Add Profilesign Editor
uestc-bbs-new/qshp-fe pull request #72
Opened 2024-04-04 16:01 UTC by Akejyo

设置里个性签名的编辑功能

![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/e5004197-6775-495e-94ba-7aed9063f4d8)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/10feec7f-60ee-4895-b04c-2e78ec600345)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/a01aa5e5-b6f6-4858-9144-9100bfa1bae7)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/2a17df72-38c8-49bd-981a-a201550e9615)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/8d626fd5-4590-4f60-aedf-2a53a7b4a462)

2024-04-04 23:05 UTC, fangjue commented on SSO/index.html
> +
怎么又有无关文件了？

2024-04-04 23:07 UTC, fangjue commented on bbs/src/components/Blacklistusers/index.tsx
这个文件跟签名有什么关系？

2024-04-04 23:11 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +                {colors.map((color) => (
颜色选择器不必按照旧版做一个一模一样的，现代浏览器都支持 `<input type="color">`，直接用浏览器自带功能就行了。

2024-04-04 23:14 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +          <Button onClick={handlePreviewButtonClick}>
旧版要手动点击“预览”，新版做成实时预览（加 debounce）。

2024-04-04 23:23 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +const smilyScaleFactor = 0.8
为什么是 0.8？

2024-04-04 23:23 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +  const [sign, setSign] = useState('之前的个人签名')
签名用 uncontrolled 方式比较合适？这样也不用再单独维护下面的 selectionStart、selectionEnd 状态了。

2024-04-04 23:27 UTC, fangjue requested changes
大概看了一下代码，还未本地测试。

2024-04-14 05:53 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +                {colors.map((color) => (
这 `<input type="color">` 我实在没搞会
它本来的样式太丑，一个方块，还需要点击一下才能打开取色器，然后我想让那个显色的小方块消失，直接打开提色器，选一个颜色点确认按钮确认，结果搞了好久没弄出来
现在是按这个按钮
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/4e70a792-5044-4f71-9f55-fde252dc653a)
弹出
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/9b908f02-b8dc-47a6-822f-534761265315)
点这个显色小块出来提色器
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/c86bd3cb-cd53-4411-910f-cce3d45139b2)

我本来还想把这提色器单独弄出来用的，不知道咋办

2024-04-14 05:54 UTC, Akejyo commented on SSO/index.html
> +
这个文件其实是由自动代码格式化导致的，其他每个文件最下面都有一个空行的，自动就把这个也带上了（

2024-04-14 05:54 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +const smilyScaleFactor = 0.8
目视（
感觉0.8的大小比较合适

2024-04-14 05:59 UTC, Akejyo commented on bbs/src/components/Blacklistusers/index.tsx
我怎么把东西分开交呢？开新的分支？
如果是开新分支的话，我是不是有多少个分支我本地就要有多少个备份？
不大懂😩

2024-04-14 07:18 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +                {colors.map((color) => (
> 这 `<input type="color">` 我实在没搞会 它本来的样式太丑，一个方块，还需要点击一下才能打开取色器，然后我想让那个显色的小方块消失，直接打开提色器，选一个颜色点确认按钮确认，结果搞了好久没弄出来 现在是按这个按钮 ![image](https://private-user-images.githubusercontent.com/91040264/322250073-4e70a792-5044-4f71-9f55-fde252dc653a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzkxMTIsIm5iZiI6MTcxMzA3ODgxMiwicGF0aCI6Ii85MTA0MDI2NC8zMjIyNTAwNzMtNGU3MGE3OTItNTA0NC00ZjcxLTlmNTUtZmRlMjUyZGM2NTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA3MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNTgzNTc3OWU0YjY3OWQ4ODk4ZGE4NTY0NDBiMzk0ODJiYTIzODlhNTRjZWMyZmFlZWE4ODUyMDE5NTU4MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQPLAFvO1nGFaVGjpBnh5zcDrfquTmGPauW6Z3vTxGY) 弹出 ![image](https://private-user-images.githubusercontent.com/91040264/322250104-9b908f02-b8dc-47a6-822f-534761265315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzkxMTIsIm5iZiI6MTcxMzA3ODgxMiwicGF0aCI6Ii85MTA0MDI2NC8zMjIyNTAxMDQtOWI5MDhmMDItYjhkYy00N2E2LTgyMmYtNTM0NzYxMjY1MzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA3MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjM0Mjk0ZDM3MTgxMmY3ZjU1M2I4OTAwMjBhYmE4NzIyNzEzNmM5NjVkYzZmN2QzYWI2M2FhNzlhZDkwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I2C8mIHni89R2I1jEColTkX-jRKi0EwmQbgnt9JV-IQ) 点这个显色小块出来提色器 ![image](https://private-user-images.githubusercontent.com/91040264/322250224-c86bd3cb-cd53-4411-910f-cce3d45139b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzkxMTIsIm5iZiI6MTcxMzA3ODgxMiwicGF0aCI6Ii85MTA0MDI2NC8zMjIyNTAyMjQtYzg2YmQzY2ItY2Q1My00NDExLTkxMGYtY2NlM2Q0NTEzOWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA3MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZjUyZTcyM2Y4NjZmYTRmODkyMWQ2ZTk0ZjM3ZWZiNzZlOTMzMGE4NDk3NGNkMTdlYzU0NGI4ODllYzQ5NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bMhqlfRFTNu4PQgOLB1xvyh6n2Hsz7pgzvW9GnGad1E)
> 
> 我本来还想把这提色器单独弄出来用的，不知道咋办

把 `<input type="color">` 叠在选择颜色按钮上（占满整个按钮的宽度/高度，并设置 opacity: 0），这样点击按钮时就会直接弹出颜色选择器，与自定义文件上传按钮时 `<input type="file">` 的用法类似。

2024-04-14 07:20 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +                {colors.map((color) => (
那我如何选择颜色呢，就是说那个“确定“按钮放在什么位置

2024-04-14 07:20 UTC, fangjue commented on SSO/index.html
> +
> 这个文件其实是由自动代码格式化导致的，其他每个文件最下面都有一个空行的，自动就把这个也带上了（

可以单独发一个 Pull request 包含运行自动代码格式化后的更改（附上代码格式化运行的命令或者执行的操作步骤），不要跟正常的修改混在一起。

2024-04-14 07:24 UTC, fangjue commented on bbs/src/components/Blacklistusers/index.tsx
> 我怎么把东西分开交呢？开新的分支？ 如果是开新分支的话，我是不是有多少个分支我本地就要有多少个备份？ 不大懂😩

开不同的分支，Git 本来就是这么用的，开多个分支本地保存的只是每个分支的差异，并不会把整个项目的源代码复制很多份。

2024-04-14 07:42 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +                {colors.map((color) => (
> 那我如何选择颜色呢，就是说那个“确定“按钮放在什么位置

理论上说不需要确定按钮，选择颜色后会触发 `<input type="color">` 的 onBlur 事件，可以测试一下不同浏览器中的表现是否一致。

2024-04-14 08:32 UTC, closed without merging

2024-04-15 00:35 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +  const [sign, setSign] = useState('之前的个人签名')
不用单独维护是？不维护这两个的话我怎么去操作文本呢？

2024-04-15 13:12 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +  const [sign, setSign] = useState('之前的个人签名')
通过 ref 直接操作 DOM。

2024-04-16 06:47 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +  const [sign, setSign] = useState('之前的个人签名')
```tsx
  const handleBoldButtonClick = () => {
    if (
      !inputRef.current ||
      !inputRef.current.selectionStart ||
      !inputRef.current.selectionEnd
    )
      return
    const newSign =
      sign.slice(0, inputRef.current.selectionStart) +
      '[b]' +
      sign.slice(
        inputRef.current.selectionStart,
        inputRef.current.selectionEnd
      ) +
      '[/b]' +
      sign.slice(inputRef.current.selectionEnd)
    setSign(newSign)
  }
  ```
  
  这种可以吗