Add Profilesign Editor
uestc-bbs-new/qshp-fe pull request #75
Opened 2024-04-16 07:02 UTC by Akejyo

```
[b]粗体[/b]
[color=#db1a1a]颜色[/color]
图片
[img=108,108]https://raw.githubusercontent.com/Akejyo/imageForBlog/master/img/shan.jpg[/img]
[img=10,10]https://raw.githubusercontent.com/Akejyo/imageForBlog/master/img/shan.jpg[/img]
[img=108,10]https://raw.githubusercontent.com/Akejyo/imageForBlog/master/img/shan.jpg[/img]
链接→[url=https://akejyo.github.io/]Akejyo[/url]
[s:11][s:25]
```
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/de22eb81-e2a0-49b6-a437-9eb719e1f7ea)

![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/7eb4097f-61bc-4a6f-9d56-9d413802a794)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/31f544ed-0336-4912-912a-972a980cdf42)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/0de1a636-53fe-4388-9663-fedd3b4907a4)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/91040264/3d09a7c7-e755-4296-8dc2-28291646cc56)

2024-04-28 13:53 UTC, fangjue requested changes
插入表情时，只有第一种兔斯基预览时能显示，后面其他类型的表情显示得不对。有没有测试过？

2024-04-28 13:53 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +const smilyScaleFactor = 0.8
经测试签名中实际显示的表情尺寸是原始尺寸，不要自做主张缩小。

2024-04-28 15:10 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +const smilyScaleFactor = 0.8
已修改

2024-04-29 12:00 UTC, fangjue requested changes

2024-04-29 12:00 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +        ?.path}" loading="lazy" style="width: 50px; height: 50px;"/>`
这里的 `width: 50px; height: 50px;` 又是怎么来的？

2024-04-29 12:08 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +        ?.path}" loading="lazy" style="width: 50px; height: 50px;"/>`
本来我看兔斯基是50px的就统一了
现在删掉了

2024-04-29 12:10 UTC, fangjue commented
输入框的逻辑有问题。

1. 光标在开头时，插入不了格式（`!inputRef.current.selectionStart` 判断不对，`selectionStart` 可以为零，表示光标在开头）。
2. 插入格式代码后，焦点不在输入框中，光标也跑到开头去了，设置 value 以后要重新设置 `selectionStart`, `selectionEnd`。

2024-04-29 12:12 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +        ?.path}" loading="lazy" style="width: 50px; height: 50px;"/>`
> 本来我看兔斯基是50px的就统一了 现在删掉了

后面还有那么多其他表情，而且表情也不一定是正方形的，这些问题自己仔细测试一下就应该发现。

2024-04-29 12:52 UTC, Akejyo commented
> 输入框的逻辑有问题。
> 
> 1. 光标在开头时，插入不了格式（`!inputRef.current.selectionStart` 判断不对，`selectionStart` 可以为零，表示光标在开头）。
> 2. 插入格式代码后，焦点不在输入框中，光标也跑到开头去了，设置 value 以后要重新设置 `selectionStart`, `selectionEnd`。

已修改

2024-04-29 12:55 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +  const [position, setPosition] = useState(0)
这个 position 渲染时用不到，用 useRef。

2024-04-29 12:55 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +    setPosition(inputRef.current.selectionEnd + 7)
不要硬编码 7。

2024-04-29 12:58 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +    setPosition(inputRef.current.selectionEnd + 7)
[b]xxx[/b] 的光标位置应当放在 [/b] 前，这样可以继续输入加粗的文本。

2024-04-29 12:59 UTC, fangjue reviewed
.

2024-04-29 13:08 UTC, Akejyo commented on bbs/src/pages/Settings/ProfileSign.tsx
> +    setPosition(inputRef.current.selectionEnd + 7)
[color]是不是同理？

2024-04-29 13:26 UTC, Akejyo commented
> .

已修改

2024-04-29 13:36 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
> +      if (position)
if (position.current)

2024-04-29 13:43 UTC, fangjue commented on bbs/src/pages/Settings/ProfileSign.tsx
>      if (imageWidth === 0 && imageHeight === 0) {
if (!imageWidth || !imageHeight)

* 必须同时指定宽高，[img] 代码不支持只指定其中一个
* 后面的 parseInt 可能返回 NaN（当 value == '' 时），这里用 ! 判断刚好。

2024-04-29 13:44 UTC, fangjue reviewed
细节问题

2024-04-29 13:53 UTC, merged